volumes:
  psql:
  pgadmin:

services:
  psql:
    image: postgres
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: m35pn92x
    networks:
      - custom

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=m35pn92x
      - POSTGRES_DB=Wishlist
    depends_on:
      - psql
    networks:
      - custom

  wishlist_app:
    image: maxxlorge/wishlist:dev
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
      - ConnectionStrings:PostgreSQL=Server=psql;Database=Wishlist;Username=postgres;Password=m35pn92x;Pooling=true;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://localhost:5000
    depends_on:
      - psql
    networks:
      custom:
        ipv4_address: 10.5.0.6

  nginx:
    image: nginx
    ports:
      - 5000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      custom:
        ipv4_address: 10.5.0.5
networks:
  custom:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
