volumes:
  psql:
  pgadmin:

secrets:
  secret.json:
    file: secret.json

services:
  psql:
    image: postgres
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      TZ: Asia/Yekaterinburg
      POSTGRES_PASSWORD: m35pn92x

  wishlist_app:
    image: maxxlorge/wishlist:dev
    restart: always
    environment:
      TZ: Asia/Yekaterinburg
      ASPNETCORE_URLS: http://localhost:5000
    depends_on:
      - psql
    secrets:
      - source: secret.json
        target: /app/secret.json
