volumes:
  psql:
  pgadmin:

secrets:
  wishlist_app_secrets:
    file: secret.json

services:
  psql:
    image: postgres
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Yekaterinburg
      POSTGRES_PASSWORD: m35pn92x

  wishlist_app:
    image: maxxlorge/wishlist:latest
    restart: always
    ports:
      - 5000:80
    environment:
      TZ: Asia/Yekaterinburg
    depends_on:
      - psql
    secrets:
      - source: wishlist_app_secrets
        target: /app/secret.json
