name: ci

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maxxlorge/wishlist:latest
  ssh:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      -
        name: deploy
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          user: ${{ secrets.SSH_USER }}
          command: |
            docker image pull maxxlorge/wishlist:latest
            docker compose up -d --remove-orphans
